# Generated by Django 4.0.6 on 2022-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subscription_id', models.CharField(default='null', max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
